apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: ${EVENT_SOURCE_NAME}
  namespace: ${ARGO_EVENTS_NAMESPACE}
spec:
  github:
    aphex-pipeline:
      # Repository configuration - update with your organization and repository
      repositories:
        - owner: ${GITHUB_OWNER}
          names:
            - ${GITHUB_REPO}
      
      # Webhook endpoint configuration
      webhook:
        endpoint: /push
        port: "12000"
        method: POST
      
      # GitHub events to listen for
      events:
        - push
        - pull_request
      
      # GitHub API token for authentication
      # This secret is created automatically by the CDK construct
      apiToken:
        name: ${GITHUB_TOKEN_SECRET_NAME}
        key: token
      
      # Webhook secret for validating GitHub webhook signatures (optional but recommended)
      # This secret is created automatically by the CDK construct
      webhookSecret:
        name: ${GITHUB_WEBHOOK_SECRET_NAME}
        key: secret
      
      # Enable insecure mode for development (disable in production)
      insecure: false
      
      # Active mode - webhook will be registered with GitHub automatically
      active: true
      
      # Content type for webhook
      contentType: json
