apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: aphex-pipeline-sensor
  namespace: argo-events
spec:
  # Define dependencies - events that this sensor listens for
  dependencies:
    - name: github-push
      eventSourceName: github
      eventName: aphex-pipeline
      filters:
        data:
          # Filter for pushes to main branch only
          - path: body.ref
            type: string
            value:
              - "refs/heads/main"
  
  # Define triggers - actions to take when dependencies are satisfied
  triggers:
    - template:
        name: aphex-pipeline-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: aphex-pipeline-
                namespace: argo
              spec:
                # Reference to the WorkflowTemplate that defines the pipeline topology
                workflowTemplateRef:
                  name: aphex-pipeline-template
                
                # Arguments passed to the workflow from the GitHub event
                arguments:
                  parameters:
                    # Commit SHA from the push event
                    - name: commit-sha
                      value: ""
                    
                    # Branch name from the push event
                    - name: branch
                      value: ""
                    
                    # Repository clone URL
                    - name: repo-url
                      value: ""
                    
                    # Repository name
                    - name: repo-name
                      value: ""
                    
                    # Pusher information
                    - name: pusher
                      value: ""
          
          # Parameters to extract from the GitHub event and inject into the workflow
          parameters:
            - src:
                dependencyName: github-push
                dataKey: body.after
              dest: spec.arguments.parameters.0.value
            
            - src:
                dependencyName: github-push
                dataKey: body.ref
              dest: spec.arguments.parameters.1.value
            
            - src:
                dependencyName: github-push
                dataKey: body.repository.clone_url
              dest: spec.arguments.parameters.2.value
            
            - src:
                dependencyName: github-push
                dataKey: body.repository.full_name
              dest: spec.arguments.parameters.3.value
            
            - src:
                dependencyName: github-push
                dataKey: body.pusher.name
              dest: spec.arguments.parameters.4.value
